name = "backing-and-score"
compatibility_date = "2024-03-29"

# Đánh dấu đây là Database D1 chính phục vụ cho biến môi trường process.env.backing_score_prod
[[d1_databases]]
binding = "backing_score_prod"
database_name = "backing-score-prod"
database_id = "9e48cd45-5444-4a63-beac-55210cf42249"
migrations_dir = "drizzle"
